version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: trash
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy 
